services:
  PostgreSQL:
    image: postgres:18
    container_name: taxi_postgres
    shm_size: 8GB
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - postgres
      - -c
      - max_wal_size=8GB
    networks:
      - taxi_net
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./data/raw/:/app/data/raw/

  ingestion:
    build:
      context: .
      dockerfile: dockerfile.ingestion
    container_name: ingestion
    env_file:
      - .env
    depends_on:
      PostgreSQL:
        condition: service_healthy
    networks:
      - taxi_net
    volumes:
      - ./scripts/:/app/scripts/
      - ./data/raw/:/app/data/raw/
      - processed_files:/app/data

  dbt:
    container_name: taxi_dbt
    build:
      context: .
      dockerfile: dockerfile.dbt
    env_file:
      - .env
    networks:
      - taxi_net
    depends_on:
      ingestion:
        condition: service_completed_successfully
    volumes:
      - ./dbt/:/app/dbt/

  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: dockerfile.jupyter
    env_file:
      - .env
    ports:
      - "8888:8888"
    depends_on:
      dbt:
        condition: service_completed_successfully
    networks:
      - taxi_net
    volumes:
      - ./notebooks:/home/jovyan/work/
    
volumes:
  postgres_data:
  processed_files:
  
networks:
  taxi_net:
    driver: bridge
    