from python:3.12-slim


run apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

run pip install --no-cache-dir \
    dbt-postgres

cmd ["dbt",\
    "build",\
    "--project-dir",\
    "/app/dbt/taxi_tlc",\
    "--profiles-dir",\
    "/app/dbt" ]