sources:
  - name: raw
    database: "{{ env_var('POSTGRES_DB') }}"
    schema: raw
    tables:
      - name: yellow_trip_records
      - name: green_trip_records
      - name: fhv_trip_records
      - name: fhvhv_trip_records