sources:
  - name: raw
    database: "{{ env_var('POSTGRES_DB') }}"
    schema: raw
    tables:
      - name: yellow_taxi_trip_records
      - name: green_taxi_trip_records
      - name: for_hire_taxi_trip_records
      - name: high_volume_taxi_trip_records