resources:
  pipelines:
    nyc_tlc_project:
      name: nyc_tlc_project_${bundle.target}
      target: ${var.schema_name}

      continuous: false
      photon: true
      channel: CURRENT
      catalog: ${var.catalog_name}
      serverless: true
      libraries:
      - glob:
          include: ../nyc_tlc_pipeline/bronze_transformations/**
      - glob:
          include: ../nyc_tlc_pipeline/silver_transformations/**
      - glob:
          include: ../nyc_tlc_pipeline/gold_transformations/**

      configuration:
        spark.sql.session.timeZone: ${var.time_zone}
        project.raw_volume_path: ${var.raw_volume_path}
        project.catalog_name: ${var.catalog_name}
        project.intial_date: ${var.initial_date}
        project.bronze_schema: ${var.bronze_schema}
        project.silver_schema: ${var.silver_schema}
        project.gold_schema: ${var.gold_schema}
